config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "breweries#index"
  get 'kaikki_bisset', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to: 'ratings#new'
  # post 'ratings', to: 'ratings#create'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  delete "memberships", to: "memberships#destroy"
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_block', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
  end

  # GET /beer_clubs/new
  def new
    ensure_that_signed_in
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
    ensure_that_signed_in
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    ensure_that_signed_in
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    ensure_that_signed_in
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    ensure_that_signed_in_as_admin
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(beer_club) do |f| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :founded %>
    <%= f.text_field :founded %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club), class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer Club', new_beer_club_path, class:"btn btn-primary" %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= "#{@beer_club.name} #{@beer_club.city}" %>
</h1>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<% if (current_user) && (not @beer_club.users.include?(current_user))%>
    <%= form_for(@membership) do |f| %>
        <% if @membership.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

              <ul>
                <% @membership.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>


        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :beer_club_id, value: @beer_club.id %>

        <div class="actions">
          <%= f.submit "Join", class:"btn btn-primary" %>
        </div>
    <% end %>
<% end %>

<% if (current_user) && @beer_club.users.include?(current_user)%>
    <%= form_for(@membership, method: "delete") do |f| %>
        <% if @membership.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

              <ul>
                <% @membership.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>


        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :beer_club_id, value: @beer_club.id %>

        <div class="actions">
          <%= f.submit "End membership", class:"btn btn-danger" %>
        </div>
    <% end %>
<% end %>

<h2>Members</h2>
<ul>
  <% @beer_club.users.each do |user| %>
      <li><%= link_to user.username, user_path(user) %></li>
  <% end %>
</ul>





<%= link_to 'Edit', edit_beer_club_path(@beer_club) %> |
<%= link_to 'Back', beer_clubs_path %>