config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "breweries#index"
  get 'kaikki_bisset', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to: 'ratings#new'
  # post 'ratings', to: 'ratings#create'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  delete "memberships", to: "memberships#destroy"
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_block', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_many :styles, through: :beers

  validates :username, uniqueness: true, length: {minimum: 3, maximum: 30}
  validates :password, format: {with: /\A(?=.{4,})(?=.*\d)(?=.*[A-Z])/x, message: 'has to be atleast 4 characters and must include an uppercase letter and a digit.'}

  has_secure_password

  include RatingAverage

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_brewery
    return nil if ratings.empty?

    ratings_of_breweries = ratings.group_by { |r| r.beer.brewery }
    averages_of_breweries = []
    ratings_of_breweries.each do |brewery, ratings|
      averages_of_breweries << {
          brewery: brewery,
          rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end
    averages_of_breweries.sort_by { |b| -b[:rating] }.first[:brewery]
  end

  def favorite_style
    return nil if ratings.empty?

    ratings_of_styles = ratings.group_by { |r| r.beer.style }
    averages_of_styles = []
    ratings_of_styles.each do |style, ratings|
      averages_of_styles << {
          style: style,
          rating: ratings.map(&:score).sum / ratings.count.to_f
      }
    end
    averages_of_styles.sort_by { |b| -b[:rating] }.first[:style]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def toggle_block
    ensure_that_signed_in_as_admin
    user = User.find(params[:id])
    user.update_attribute :blocked, (not user.blocked)

    new_status = user.blocked? ? "frozen" : "unfrozen"

    redirect_to :back, notice:"User freeze status changed to #{new_status}"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      session[:user_id] = nil
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @user, notice: "You can only delete your own user! Shame."
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @user.new_record? %>
        <div class="field">
          <%= f.label :username %>
          <%= f.text_field :username %>
        </div>
    <% end %>

    <div class="field">
      <% if @user.new_record? %>
          <%= f.label :password %><br/>
      <% else %>
          <%= f.label :password, "New password" %><br/>
      <% end %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit class:"btn btn-primary" %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td>
          <% if user.blocked? && current_user.admin? %>
              <span class="label label-info">Frozen</span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @user.username %>
  <% if @user.blocked? && current_user.admin?%>
      <span class="label label-info">Frozen</span>
  <% end %>
</h1>

<p>
  Ratings: <%= @user.ratings.count %>
</p>
<p>
  Average rating: <%= @user.average_rating %>
</p>

<% unless @user.favorite_style.nil? %>
    <p>
      Favorite style: <%= @user.favorite_style %>
    </p>
<% end %>

<% unless @user.favorite_brewery.nil? %>
    <p>
      Favorite Brewery: <%= @user.favorite_brewery %>
    </p>
<% end %>

<p>
  <% if @user.beer_clubs.empty? %>
      Not a member of any club.
  <% else %>
      Member of
  <% end %>


  <% @user.beer_clubs.each do |beerClub| %>
      <%= link_to "#{beerClub.name}", beer_club_path(beerClub) %>
  <% end %>
</p>

<ul>
  <% @user.ratings.each do |rating| %>
      <li><%= rating %>
        <% if @user == current_user %>
            <%= link_to "delete", rating, method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
      </li>
  <% end %>
</ul>

<% if current_user && current_user.admin? %>
    <p>
      <% if @user.blocked? %>
          <%= link_to "Unfreeze account", toggle_block_user_path(@user.id), method: :post, class: "btn btn-danger" %>
      <% else %>
          <%= link_to "Freeze account", toggle_block_user_path(@user.id), method: :post, class: "btn btn-danger" %>
      <% end %>
    </p>
<% end %>

<% if @user == current_user %>
    <%= link_to 'Edit', edit_user_path(@user) %>
    <%= link_to 'Destroy', @user, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>


|
<%= link_to 'Back', users_path %>