config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "breweries#index"
  get 'kaikki_bisset', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to: 'ratings#new'
  # post 'ratings', to: 'ratings#create'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  delete "memberships", to: "memberships#destroy"
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_block', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'

end

app/models/brewery.rb
class Brewery < ApplicationRecord
  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: {greater_than_or_equal_to: 1042,
                                  only_integer: true}
  validate :less_than_this_year, on: :create

  include RatingAverage

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }


  def less_than_this_year
    if year > Time.now.year
      errors.add(:year, "Year can't be set in the future.")
    end
  end

  def to_s
    "#{name}"
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all

    order = params[:order] || "name"


    @active_breweries = case order
                          when 'name' then
                            @active_breweries.sort_by { |b| b.name }
                          when 'year' then
                            @active_breweries.sort_by { |b| b.year }
                        end

    @retired_breweries = case order
                           when 'name' then
                             @retired_breweries.sort_by { |b| b.name }
                           when 'year' then
                             @retired_breweries.sort_by { |b| b.year }
                         end

    if session[:breweriesOrder]
      if session[:breweriesOrder] == order
        @active_breweries = @active_breweries.reverse
        @retired_breweries = @retired_breweries.reverse
        session.delete(:breweriesOrder)
      else
        session[:breweriesOrder] = order
      end

    else
        session[:breweriesOrder] = order
    end

  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    ensure_that_signed_in
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
    ensure_that_signed_in
  end

  def list
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice: "brewery activity status changed to #{new_status}"
  end

  # POST /breweries
  # POST /breweries.json
  def create
    ensure_that_signed_in
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ensure_that_signed_in
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ensure_that_signed_in_as_admin
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  private


end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(brewery) do |f| %>
    <% if brewery.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

          <ul>
            <% brewery.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :year %>
      <%= f.number_field :year %>
    </div>

    <div class="field">
      <%= f.label :active %>
      <%= f.check_box :active %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th> <%= link_to 'Name', breweries_path(order:"name") %> </th>
    <th> <%= link_to 'Year', breweries_path(order:"year") %> </th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery), class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breweries</h1>

<h2>Active</h2>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= render 'list', breweries: @retired_breweries %>

<br>

<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-primary" %>

<%= link_to "List of all beers", beers_path %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Year</a> </th>
    <th> <a href="#" id="beers">Beers</a> </th>
    <th> <a href="#" id="status">Status</a> </th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @brewery.name %>
  <% unless @brewery.active %>
      <span class="label label-info">retired</span>
  <% end %>
</h2>

<p>
  Established in <%= @brewery.year %>
</p>

<p>
  Number of beers <%= @brewery.beers.count %>
</p>

<ul>
  <% @brewery.beers.each do |beer| %>
      <li>
        <%= link_to beer.name, beer %>
      </li>
  <% end %>
</ul>

<p>
  <% if @brewery.ratings.empty? %>
      Beers have not yet been rated!
  <% else %>
      Has <%= pluralize(@brewery.ratings.size, "rating") %>, average <%= @brewery.average_rating %>
  <% end %>
</p>

<p>
  <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %>
</p>

<p>
  <%= link_to "List of all beers", beers_path %>
</p>


<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>